## Implementando neurônios


Vamos implementar o neurônio destacado

![REDE NEURAL](https://i.imgur.com/eUu71E1.png)

In [3]:
#vamos supor que estamos fazendo um neurônio que esteja implementado no meio de uma rede neural, com conexões de entrada e saída nele.
#nesse caso, todos os neurônios tem conexões com cada neurônio prévio a ele, vamos supor que tenham 3 neurônios conectados que estejam
#dando entrada nesse neurônio que vamos fazer.

#esses inputs são as saidas dos três neurônios previos
inputs = [1, 2, 3]

#cada input tem um peso associado a ele
weights = [0.2, 0.8, -0.5]

#cada neurônio tem um bias único, como estamos fazendo um único, neurônio, só há 1 bias
bias = 2

#a saida do neurônio é a soma dos produtos de cada dado de entrada com seu respectivo peso com o bias
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias

output

2.3

Nosso neurônio ficou com essa cara

![NEURONIO](https://i.imgur.com/DB6FAYC.png)

 Agora vamos modelar um neurônio da camada de saída:
 
![REDE NEURAL](https://i.imgur.com/NEByrWc.png)

In [4]:
#A mesma coisa do outro neurônio, a diferença é que agora o neurônio está tendo 4 entradas de uma camada oculta.

#esses inputs são as saidas dos quatro neurônios previos
inputs = [1, 2, 3, 2.5]

#cada input tem um peso associado a ele
weights = [0.2, 0.8, -0.5, 1.0]

#cada neurônio tem um bias único
bias = 2

#a saida do neurônio é a soma dos produtos de cada dado de entrada com seu respectivo peso com o bias
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias

output

4.8

Nosso neurônio ficou assim:

![NEURONIO](https://i.imgur.com/HzH98wE.png)

## Implementando camadas

Vamos implementar a camada de saida:

![REDE NEURAL](https://i.imgur.com/GDsbq06.png)

In [4]:
#Sao 3 neuronios de saida, note que cada um tem 4 entradas
#A lógica dos neurônios continua sendo a mesma que já foi implementada.

#esses inputs são as saidas dos quatro neurônios previos
inputs = [1, 2, 3, 2.5]

#cada input tem um peso associado a ele, como sao 3 neurônios, teremos 3 listas de pesos
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

#cada neurônio tem um bias único (menos os da camada de entrada, entao serao 3 biases)
biases = [2, 3, 0.5]

#a saida do neurônio é a soma dos produtos de cada dado de entrada com seu respectivo peso com o bias
#saida = entrada * peso + bias 

#essa funcao percorre a lista de pesos e biases e nos retorna as saidas dos neuronios
#resultado_camada é a lista em que vamos guardar o resultado de cada camada
resultado_camada = []
#o que o zip() faz é combinar duas listas em uma, formando uma lista de tuplas, 
#assim dá pra percorrer as duas listas paralelamente
for peso_neuronio, bias_neuronio in zip(weights, biases):
    #inicializa a saida do neuronio como 0
    saida_neuronio = 0
    #aqui de novo ele faz o zip, so que agora com os inputs do neuronio e o peso,
    #que foi usado no zip acima 
    for entrada_neuronio, peso in zip(inputs, peso_neuronio):
        #aqui fazemos o processo para calcular a saida do neuronio, multiplicando as 
        #entradas e seus respectivos pesos
        saida_neuronio += entrada_neuronio*peso
    #aqui ele pega o resultado da multiplicacao e soma com o bias do neuronio
    saida_neuronio += bias_neuronio
    #acrescenta a saida do neuronio na lista do resultado das camadas
    resultado_camada.append(saida_neuronio)

print(resultado_camada)    

[4.8, 1.21, 2.385]


O primeiro neurônio ficou assim:

![REDE NEURAL](https://i.imgur.com/Bi6fovb.png)

![REDE NEURAL](https://i.imgur.com/TonkYba.png)

### Usando o Dot Product

#### Exemplo de uso em um único neurônio

In [5]:
#dot product é a função do numpy que faz multiplicação entre vetores
import numpy as np

#vamos simplificar para esse teste para um neurônio só
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

#na função passamos o array A, depois o array B
resultado = np.dot(inputs, weights) + bias

resultado

4.8

#### Exemplo de uso em uma camada

In [6]:
import numpy as np

inputs = [1, 2, 3, 2.5]

weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 3, 0.5]

#A ORDEM QUE PASSAMOS ESSES ARRAY IMPORTA NESSE CASO,
#O PRIMEIRO ELEMENTO QUE VC PASSA É A FORMA COMO O 
#RETORNO VAI SER INDEXADO,
#COMO TEMOS TRÊS NEURÔNIOS, QUEREMOS QUE ELES 
#SEJAM INDEXADOS POR ESSES TRÊS SETS DE PESOS

resultado = np.dot(weights, inputs) + biases

resultado

array([4.8  , 1.21 , 2.385])

### Exemplo de uso de entradas em lotes

In [3]:
import numpy as np

#agora estamos passando as entradas em lotes, mas o cenário da rede neural continuaria o mesmo,
#seriam três neurônios enviando suas entradas em lotes 
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 3, 0.5]

#agora temos que pegar e fazer a transposta das entradas, então pegamos e transformamos os inputs em um array do numpy e usamos o .T para transposta
#fazemos isso porque antes, os pesos eram uma matriz e as entradas eram um simples vetor, o shape da matriz era (3,4) - 3 linhas com 4 elementos em cada e o shape do vetor era
#(,4) - 1 dimensão com 4 elementos, nesse sentido o .dot funcionava, agora com os lotes, o shape da matriz de pesos é (3,4) e o da matriz de entrada também é (3,4), no dotproduct
#isso não vai servir porque temos que ter o número de colunas da primeira (4) tem que ser igual ao numero de linhas da segunda, fazendo a transposta, a matriz que antes era (3,4)
#passa a ser (4,3) o que faz com que o número de colunas da primeira (4), fiquem igual ao numero de linhas da segunda (4). Nisso a matriz formada é uma com o número de linhas da primeira
#e o número de colunas da segunda, nesse caso, será uma matriz 3 x 3.
resultado = np.dot(weights, np.array(inputs).T) + biases

#o bias é adicionada em cada linha, então ele pega a linha 1 da matriz resultante e adiciona em cada elemento o bias daquela posição.
resultado

array([[ 4.8  ,  9.9  , -0.09 ],
       [ 0.21 , -1.81 , -1.449],
       [ 3.885,  2.7  ,  0.026]])

### Exemplo de uso de lotes em mais de uma camada

In [6]:
import numpy as np

#agora estamos passando as entradas em lotes, mas o cenário da rede neural continuaria o mesmo,
#seriam três neurônios enviando suas entradas em lotes 
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

#na primeira camada vamos ter 
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 3, 0.5]

weights2 = [
    [0.1, -0.14, -0.14, 0.5],
    [-0.5, -0.12, -0.33, -0.5],
    [-0.44, 0.73, -0.13, 0.87]
]

biases2 = [-1, 2, -0.5]

resultado_camada1 = np.dot(weights, np.array(inputs).T) + biases

resultado_camada2 = np.dot(weights2, np.array(inputs).T) + biases2

print(resultado_camada1)

print(resultado_camada2)

[[ 4.8    9.9   -0.09 ]
 [ 0.21  -1.81  -1.449]
 [ 3.885  2.7    0.026]]
[[-0.35   2.64  -1.89 ]
 [-3.98  -0.27  -0.763]
 [ 1.805  6.64   1.006]]


### Criando um objeto de camada

In [5]:
import numpy as np

#estamos setando a seed do random para 0
np.random.seed(0)

X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        #essa funcao np.random.randn gera números da distribuição normal, e podemos passar o shape do array que ela vai gerar, nesse caso vamos
        #pedir para gerar um array com linhas sendo o número de entradas e colunas sendo o número de neurônios
        #multiplicamos por 0.1 para normalizar os valores e eles ficarem entre -1 e 1, visto que se não normalizarmos podemos sobrecarregar a rede
        #e a capacidade dela
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        #aqui nos formamos a matriz de biases para os neuronios, o np.zeros retorna pra gente um array preenchido com 0 no shape que informarmos, no caso,
        #são o número de neurônios
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        #aqui temos a saida, fazemos a multiplicação das entradas com seus pesos e acrescentamos os biases
        self.output = np.dot(inputs, self.weights) + self.biases

In [6]:
#aqui criamos duas camadas
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

#aqui usamos o método para produzir as saidas da primeira camada
layer1.forward(X)
print("Saida da camada 1")
print(layer1.output)
print("Saida da camada 2")
#aqui usamos a saida da primeira camada e passamos para a segunda camada 
layer2.forward(layer1.output)
print(layer2.output)

Saida da camada 1
[[-0.12088873  0.43034258  0.53633118 -0.08341587 -0.05415085]
 [-0.20888481 -0.20167584  0.72514546 -0.33075799  0.2127461 ]
 [-0.62566662  0.76797946  0.48532311 -0.14053423 -0.40505212]]
Saida da camada 2
[[-0.08420453 -0.03136665]
 [-0.08298085  0.057347  ]
 [-0.17690916 -0.09676833]]


### Criando uma Função de Ativação

In [9]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

#nnfs é uma biblioteca criada pelo proprio canal do curso,
#ela tem funcoes que auxiliam no processo de aprendizado de redes neurais
#nnfs vem de neural networks from scratch

#aqui iniciamos o nnfs
nnfs.init()

#aqui ele cria dados de exemplo, usando a biblitoeca nnfs
X, y = spiral_data(100,3)


class Ativacao_ReLu:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

layer1 = Layer_Dense(2,5)
activation1 = Ativacao_ReLu()

layer1.forward(X)
print('#########RESULTADOS SEM FUNCAO DE ATIVACAO RELU#########')
print(layer1.output)
print('#########RESULTADOS COM FUNCAO DE ATIVACAO RELU#########')
activation1.forward(layer1.output)
print(activation1.output)

#########RESULTADOS SEM FUNCAO DE ATIVACAO RELU#########
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
#########RESULTADOS COM FUNCAO DE ATIVACAO RELU#########
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-0